const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: "https://img.kidspot.com.au/iLk5LIVi/w643-h428-cfill-q90/kk/2015/03/buttermilk_pancakes_final-607368-1.jpg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: "\https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6UsffqYkdIq3N3Oeh5VQ-q17s7DwzxqmVS1Yy7Wjh51p76ocNN3RpVph66iiQ8WI66jZN-mMOZgw&usqp=CAU&ec=48600113",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: "https://i2.wp.com/funmoneymom.com/wp-content/uploads/2021/03/IMG_9553.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPZ07B3O33KI5DxvUzYcWotpLVunXt_p01wxMoHNfvz5VsCexSBXY29dfoRZa_Wx5ptudFNs9knbc&usqp=CAU&ec=48600113",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: "https://static.toiimg.com/thumb/62457617.cms?resizemode=4&width=1200",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJPOUyl2aV7ccUAcHjkq7DnQji_720JX47Yz6ZoC_a7g&usqp=CAU&ec=48600113",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTscY3LAT_CCoak6sGgrc0qCHH53BGv-Qu4k2SJ_xoGMUIgX4JzSzPBXfRW8iGdi1GYxHjzdTDWmcA&usqp=CAU&ec=48600113",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTscY3LAT_CCoak6sGgrc0qCHH53BGv-Qu4k2SJ_xoGMUIgX4JzSzPBXfRW8iGdi1GYxHjzdTDWmcA&usqp=CAU&ec=48600113",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGnnAw1mh-6-HR9K7ShbNfgTauSTj5exiiH3Ld_o0ZfQ&usqp=CAU&ec=48600113",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
